local config = require('org-super-agenda.config')

describe('config.setup', function()
  local defaults = vim.deepcopy(config.defaults)

  after_each(function()
    config.setup(vim.deepcopy(defaults))
  end)

  it('overrides values', function()
    config.setup({ upcoming_days = 5, keymaps = { reload = 'x' } })
    local cfg = config.get()
    assert.equals(5, cfg.upcoming_days)
    assert.equals('x', cfg.keymaps.reload)
  end)

  it('ships clock keymaps defaults', function()
    config.setup(vim.deepcopy(defaults))
    local cfg = config.get()
    assert.equals('I', cfg.keymaps.clock_in)
    assert.equals('O', cfg.keymaps.clock_out)
    assert.equals('X', cfg.keymaps.clock_cancel)
    assert.equals('gI', cfg.keymaps.clock_goto)
    assert.equals('gX', cfg.keymaps.reset_hidden)
  end)
end)
